# Generated by Django 2.2.10 on 2020-11-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_auto_20201110_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_info',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
